name: pomodoro
description: Projeto desenvolvido para o programa de Dev Flutter da Inmetrics.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  percent_indicator: ^4.0.0
  audioplayers: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/pomodoro.png
    - assets/sounds/sound_1.mp3
    - assets/sounds/sound_2.mp3
